"""empty message

Revision ID: 317849033928
Revises: 6f4baa2213b9
Create Date: 2023-06-13 23:05:31.131445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317849033928'
down_revision = '6f4baa2213b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_hike_id_fkey', type_='foreignkey')
        batch_op.drop_column('hike_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hike_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('categories_hike_id_fkey', 'hikes', ['hike_id'], ['id'])

    # ### end Alembic commands ###
