"""empty message

Revision ID: fb1efe19f5f4
Revises: 5ce1f568ad99
Create Date: 2023-06-29 15:57:28.121435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1efe19f5f4'
down_revision = '5ce1f568ad99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hikes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hikes', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
